### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by TLFPss** [zhoux85/STAligner#1]
Hello, after installing according to the pipeline, `import STAligner` reports an error:

`ModuleNotFoundError: No module named 'intervaltree'`

Using `conda install -c conda-forge xxx` to directly install the missing package does not seem to solve this problem, because then other `ModuleNotFoundError` will appear. And it will change the versions of existing packages, causing some new problems:
```
ModuleNotFoundError: No module named 'annoy'

ModuleNotFoundError: No module named 'hnswlib'

SystemError: initialization of _internal failed without raising an exception

ModuleNotFoundError: No module named 'torch_sparse'
```
What should I do to install your tool

**Comment by zhoux85** [comment]
Thanks for the report! The 'intervaltree' package is not used in current version. I have removed the legacy code and updated the tool. Please reinstall it.

**Comment by TLFPss** [comment]
Thank you, I successfully installed and imported.
