### ISSUE TITLE
example data for Tutorial 5: Spatial domain guided 3D slices alignment

### ISSUE THREAD

**Issue by mkunst23** [zhoux85/STAligner#11]
Hi,

Is there a way to provide the SlideSeq data for tutorial 5 as h5ad files? The link provided only has the original data. Also, a more general question. Does the structure just for aligned needs to be present in all sections? Or can I provide multiple structures? I have a rather large dataset (whole brain) and one region will not be found in all sections.

Thanks,
Michael

**Comment by zhoux85** [comment]
Hi. I have uploaded the h5ad files to https://drive.google.com/file/d/1xtOBHgx2JNcgTp5q-hSFVAZsdC6ic05S/view?usp=sharing
We just need a common structure (landmark domain) between the two adjacent sections, not all sections. A common structure across all sections can make the 3D structure easy to recognise, but not nessary.

**Comment by mkunst23** [comment]
Great,

Thanks for the quick response!
