### ISSUE TITLE
Inconsistency in tutorial workflows

### ISSUE THREAD

**Issue by t-a-m-i** [zhoux85/STAligner#27]
Hi, great package you developed! 

I´m currently running some tutorials to make sure my environment setup worked properly and to understand your workflow. I´m just a bit confused about why you do HVGs -> normalize -> log1p in tutorial2 and normalize -> log1p -> HVGs in tutorial4. Could you please elaborate on that a bit? 

As far as I understand from the documentation of scanpy, generally logarithmized data is expected for HVGs, except when flavor='seurat_v3'/'seurat_v3_paper', in which count data is expected. (https://scanpy.readthedocs.io/en/stable/generated/scanpy.pp.highly_variable_genes.html)
Am I missing something crucial? Thanks!

**Comment by zhoux85** [comment]
Hi. Please follow the sequence from the documentation of scanpy: `normalize -> log1p -> HVGs`. I think both workflow works and the results don't make much difference.
