### ISSUE TITLE
Processing error with MOSTA mouse embryo samples

### ISSUE THREAD

**Issue by vladimirkovacevic** [zhoux85/STAligner#3]
Hi!

We wanted to run 4 samples of the  Mouse embryo (9.5 - 12.5) from [MOSTA](https://db.cngb.org/stomics/mosta/spatial/) that you've used in the paper but the GPU (24 GB of memory, on AWS g5.8xlarge) runs out of memory. On this machine we managed to process only E9.5 and E10.5 together if we add E11.5 the code crushes with the error:
```
OutOfMemoryError: CUDA out of memory. Tried to allocate 4.72 GiB (GPU 0; 22.06 GiB total capacity; 14.66 GiB already allocated; 1.74 GiB free; 19.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
Setting: `os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:512"` does not work.
We kill the kernel after the unsuccessful run and make sure vram is free with nvidia-smi.

STAligner converts all cell-gene matrices from sparse dense and puts them to GPU memory which requires a huge amount of it. Do you have any suggestions on how to perform the processing? Have you considered splitting them into more than one GPU unit?

**Comment by zhoux85** [comment]
Hi. I run the Mouse embryo datasets on a GPU with 24 GB of memory, which only use 8867MiB GPU memory. After concatenating the 4 slices, the size of adata_concat is (95896 cell, 693 gene). Key steps are as follows:

```
STAligner.Cal_Spatial_Net(adata, rad_cutoff=1.3) ## about 4 neighbors per cell on average

iter_comb = [(0, 3), (1, 3), (2, 3)]
adata_concat = STAligner.train_STAligner(adata_concat, verbose=True, knn_neigh = 100, n_epochs = 1000, iter_comb = iter_comb,  margin=2.5,  device=used_device)
```

Hope it helps !

**Comment by vladimirkovacevic** [comment]
Thank you very much, we'll try to run it and let you know. 

Two more things:
1. In MOSTA there are more than one mouse embryo sample for every day. Have you used these ones?
- E9.5_E1S1.MOSTA.h5ad
- E10.5_E1S1.MOSTA.h5ad
- E11.5_E1S1.MOSTA.h5ad
- E12.5_E1S1.MOSTA.h5ad
2. The samples in MOSTA are normalized, have you switched off normalization for them before processing?

**Comment by vladimirkovacevic** [comment]
With the changes you've provided, we managed to complete the processing for all 4 samples but the output does not look like the one reported in the paper. Please have a [look](https://drive.google.com/file/d/18Z0a8COKDOKP344H-dvEYA1VntOtcjAa/view?usp=sharing).

STAligner.Cal_Spatial_Net(adata, rad_cutoff=1.3)
sc.pp.highly_variable_genes(adata, flavor="seurat", n_top_genes=5000)
iter_comb = [(0, 3), (1, 3), (2, 3)]
adata_concat = STAligner.train_STAligner(adata_concat, verbose=True, knn_neigh = 100, device=used_device, n_epochs=1000, iter_comb=iter_comb, margin=2.5)
num_cluster=13 

Do you have any more suggestions on how to improve the results?

**Comment by zhoux85** [comment]
Hi. 
1. We used the slice E10.5_E2S1 instead of E10.5_E1S1 to find more common tissue structures.
2. Use `adata.X = adata.layers['count']` to load the raw counts matrix.
3. We used louvain to obtain the clusters with resolution=0.4.

We uploaded a new tutorial for reference: https://staligner.readthedocs.io/en/latest/Tutorial_embryo.html
