### ISSUE TITLE
Questionable ST quality on drosophylia sample

### ISSUE THREAD

**Issue by vladimirkovacevic** [zhoux85/STAligner#4]
We wanted to test STAligner with drosophila sample [E14-16h_a_count_normal_stereoseq.h5ad](https://db.cngb.org/stomics/flysta3d/). adata.obs['slice_ID'] denotes a part of anndata object that refers to 1 of 16 slices. Raw counts are available in adata.layers['raw_counts'] and spatial info is in adata.obs.['raw_x', 'raw_y'].
We run the default configuration with rad_cutoff=30 (each cell has approx. 7.5 neighbors) and obtained the following [result](https://drive.google.com/file/d/1aI5LutFsLjaWjsWkqPTVM-Fxtzh-bVC1/view?usp=share_link).
Is this expected behaviour and is there something that might be done to improve the quality?

Here is the [ground-truth](https://drive.google.com/file/d/1cFfPtHnnF7UEoElyj3Ib-ZHOonvJOcTQ/view?usp=share_link) for these samples.
Here is the source code that we used to load the data:
```
from scipy import sparse
Batch_list = []
adj_list = []
adata_whole = sc.read('/goofys/Samples/Stereo_seq/flysta3d/E14-16h_a_count_normal_stereoseq.h5ad') #edit
section_ids = list(adata_whole.obs['slice_ID'].cat.categories)
adata_whole.X = adata_whole.layers['raw_counts'] # select raw counts gene matrix
adata_whole.X = sparse.csr_matrix(adata_whole.X) # STAligner expects to find sparse matrix here

for section_id in section_ids:
    adata = adata_whole[adata_whole.obs['slice_ID'] == section_id]
    adata.obsm['spatial'] = adata.obs[['raw_x', 'raw_y']].values
    adata.uns = {}
    adata.var_names_make_unique(join="++")

    # read the annotation
    adata.obs['Ground Truth'] = adata.obs['annotation']
        
    # make spot name unique
    adata.obs_names = [x+'_'+section_id for x in adata.obs_names]
    
    # Constructing the spatial network
    print("Cal Spa Net")
    STAligner.Cal_Spatial_Net(adata, rad_cutoff=30) # the spatial network are saved in adata.uns[‘adj’]
    
    # Normalization
    sc.pp.highly_variable_genes(adata, flavor="seurat_v3", n_top_genes=5000)
    sc.pp.normalize_total(adata, target_sum=1e4)
    sc.pp.log1p(adata)
    adata = adata[:, adata.var['highly_variable']] 
    
    adj_list.append(adata.uns['adj'])
    Batch_list.append(adata)

adata_concat = STAligner.train_STAligner(adata_concat, verbose=True, knn_neigh = 50, device=used_device)
```
We run it with knn_neigh = 50 since each sample has around 500 obs
Rest of the code is the same as in Tutorial_DLPFC

**Comment by zhoux85** [comment]
Hi. Suggestions below may be helpful.

- The `n_top_genes` is very import. We need to increase the number to ensure enough common HVGs (~1000) in the combined matrix. In the drosophila dataset, we suggest `n_top_genes > 8000`.

- `rad_cutoff=25`  #each cell has approx. 4 neighbors

- `iter_comb = [(0, 8), (1, 8), (2, 8), (3, 8), (4, 8), (5, 8), (6, 8), (7, 8), (9, 8), (10, 8), (11, 8), (12, 8), (13, 8), (14, 8), (15, 8)]` #middle slice 8 has the most common domains, use it as reference
